### ISSUE TITLE
Identify geography fields on upload

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#49]
At least V2, but we talked about having Geomancer take a guess at geography fields
on import.  Would be a wonderful feature to have the UI provide a menu of data sources
based on recognized geography in the uploaded spreadsheet (with the option, of course, to 
override the recognized fields and designate them)

**Comment by derekeder** [comment]
We're going to handle this by taking a sample of the selected column, and running it through a combination of regex validations and gazetteers. 

For example, US Census has a list of all valid counties that we can check against (both name and FIPS Code). For zip codes, we can validate it with this regex: `(\d{5})-(\d{4})$`

**Comment by derekeder** [comment]
Closed by #65
