### ISSUE TITLE
ACS data point name truncated

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#52]
"Median Value (Dollars)" should read "MEDIAN HOUSING VALUE OF OWNER-OCCUPIED HOUSING UNITS (DOLLARS)" (I believe.)

**Comment by evz** [comment]
@tthibo Do we want to pursue cleaning this up any further? It seems like there's not much we can do without manually overriding the info that we are getting from CensusReporter

**Comment by tthibo** [comment]
Is the modification for BaseMancer to allow manual naming in place? I do think this one is worth a manual override. Guess technically is should be "Median Value, Owner-Occupied Housing Units." That's not too long, is it?
