### ISSUE TITLE
Bureau of Economic Analysis mancer

### ISSUE THREAD

**Issue by derekeder** [associatedpress/geomancer#69]
Bureau of Economic Analysis has state level data that includes:

* Nominal GDP     
* Personal Income - Per Capita    
* Personal Income - Total     
* Real GDP    
* Real GDP - Per Capita   

An API key is required. Registration: http://www.bea.gov/API/signup/index.cfm

Related to #17

**Comment by evz** [comment]
Closed with #65

**Comment by cathydeng** [comment]
here are some other stats from BEA that we could add if there is interest:
http://www.bea.gov/itable/iTable.cfm?ReqID=70&step=1#reqid=70&step=1&isuri=1
