### ISSUE TITLE
Header for add data screen is misnumbered

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#71]
Step 3 of the upload process has this header:
2. Add data

Should be
3. Add data

**Comment by evz** [comment]
This appears to be fixed.

**Comment by tthibo** [comment]
![screen shot 2015-02-13 at 3 56 19 pm](https://cloud.githubusercontent.com/assets/217394/6195944/f6111ee8-b398-11e4-953d-9c5720cf8085.png)
