### ISSUE TITLE
Excel file format not matching file extension error on IE

### ISSUE THREAD

**Issue by bobweston** [associatedpress/geomancer#72]
On Internet Explorer 9 and Firefox 35.01 on Windows:

When trying to open the excel file generated by Geomancer, I get the following popup message:

"The file you are trying to open is in a different format that specified by the file extension. Verify that the file is not corrupted and is onfrom a trusted source before opening the file. Do you want to open the file now?"

Despite the popup warning, the file opened as expected in Excel.

**Comment by evz** [comment]
The way this works under the hood is, when the application is ready to create the output file, it checks the file extension of the input file and then chooses one of three different ways to create output, one for old Excel ('.xls') one for new Excel ('.xlsx') and one for plain old CSV. It's possible that something is getting confused by a doubled file extension or something like that. Any chance you have a sample file we could test this with?

**Comment by bobweston** [comment]
Hey Derek,

Try this:
http://hosted.ap.org/specials/interactives/aaaaa.xlsx

**Comment by evz** [comment]
@bobweston Ah, OK upon closer examination of your original issue, I think I tracked it down. It has to do with the header that the web server generates for those file types. I had files with ``.xls`` and ``.xlsx`` using the same header (which is not correct). If you don't mind trying again, I think it should be fixed.
