### ISSUE TITLE
Error for "city, state" geography

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#77]
Attempted to work with the failed banks list from the Examples directory:
https://github.com/associatedpress/geomancer/blob/master/examples/fdic_failed_banks.xlsx 

Attempted to add "Median value (dollars)"

Received error:
Census Reporter API returned an error message: { "error": "The ACS 2013 5-year release doesn't include GeoID(s) 16000US2148000." }

**Comment by evz** [comment]
I found that Louisville seems to be missing from CensusReporter, in general:

https://github.com/censusreporter/census-api/issues/24

I'll put a fix in to cover us for the demo.

**Comment by evz** [comment]
I'll wait to close this after we hear back from the CensusReporter guys.

**Comment by tthibo** [comment]
Confirming that Eric's fix worked. Not sure if you still want to leave this open until hearing from CensusReporter, though.

**Comment by derekeder** [comment]
Think we can close this issue on our end now that we are handling this case.
