### ISSUE TITLE
Question about census values returned

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#79]
Not sure if this is a geomancer issue or Census Reporter, but when I uploaded the
FEMA Recoupment data set from the Examples directory and tried to add Median home
value, I received some questionable values, including multiple instances if "1000001" with
no margin of error.

![screen shot 2015-03-03 at 8 20 19 pm](https://cloud.githubusercontent.com/assets/217394/6476991/c6305fec-c1e2-11e4-912d-eb548b4f1719.png)

**Comment by evz** [comment]
Looks like that's what we're getting back from Census Reporter: 

![screen shot 2015-03-04 at 2 40 56 pm](https://cloud.githubusercontent.com/assets/551491/6492937/946ef000-c27c-11e4-84d0-83c2d9c16c33.png)

**Comment by derekeder** [comment]
Not much we can do on our end about this. Closing.
