### ISSUE TITLE
Header disappearing

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#87]
Header row not present in downloaded data.

To replicate:
Upload https://github.com/associatedpress/geomancer/blob/master/examples/Eqi_results_2013July22.xlsx 

Add Median House value.

Mancing succeeds, but the new spreadsheet has no header.

**Comment by evz** [comment]
I don't know how we were making this happen last night because I can't make it happen again this morning. One difference is that I am not using Excel to open the resulting file (I only have LibreOffice). I don't know if that would make the difference.

**Comment by derekeder** [comment]
@tthibo tested this out, and was unable to reproduce. Is it possible the header row was being skipped when importing into Excel/LibreOffice?

**Comment by tthibo** [comment]
Not sure what was going on there, but I'm not seeing the issue any longer. Closing.
