### ISSUE TITLE
Not counting added columns correctly when columns already exist

### ISSUE THREAD

**Issue by evz** [associatedpress/geomancer#88]
So, discovered when trying to figure out what was happening with #87 that, when you upload a spreadsheet that you've already manced, Geomancer will not re-append columns which it has already appended (which is good) but it results in a confusing message on the download page:

![screen shot 2015-03-06 at 6 40 13 am](https://cloud.githubusercontent.com/assets/551491/6524826/0d73680a-c3cc-11e4-948d-5f25fe91186d.png)

To replicate, mance a spreadsheet, download the results, then use that spreadsheet to mance a second time selecting the same columns to append. You'll end up with the same spreadsheet you uploaded the first time but with the slightly confusing error message. This could also be confusing if a user is trying to use that first spreadsheet to mance with a difference geography column (because the values will be from the first mancing session)

**Comment by derekeder** [comment]
We can address this issue by appending the `geo-type` we're matching on (city, state, etc) in the column header of the data we're adding. Something like this:

Gini Index of Income Inequality (State)

or 

Federal Assistance (County)
